### ISSUE TITLE
Update the default favicon

### ISSUE THREAD

**Issue by parthpanchal123** [gouravkhunger/nextjs-strikeit#6]
How about this for a favicon ? 

![image](https://user-images.githubusercontent.com/20091596/135748031-c6548986-8340-42d0-b4e5-5295f7471417.png)
Attribution : <div>Icons made by <a href="https://www.flaticon.com/authors/surang" title="surang">surang</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

**Comment by gouravkhunger** [comment]
Great, go ahead! Do the same as you did in the birthday wish repo :)
