### ISSUE TITLE
Update performance

### ISSUE THREAD

**Issue by luisfuentech** [gouravkhunger/nextjs-strikeit#9]
1. We could remove the second `setTimeout` (cotime) and improve the performance, doing both things (copy text and showing up) in a single one

![imagen](https://user-images.githubusercontent.com/39889256/135769981-1509788f-2ca6-457a-85d9-f8a3ea5e7376.png)

2. We could use the new JS sintax and make a code better readable
![imagen](https://user-images.githubusercontent.com/39889256/135770005-9e2864f2-6a57-41e3-806d-67311806e836.png)

**Comment by gouravkhunger** [comment]
Thank you :)
